spring:
  # database:
  datasource:
    url: jdbc:h2:mem:beneficiary-db
  h2:
    console:
      enabled: true


  cloud:
    config:
      enabled: false
# port:
server:
  port: 8081

# resolve IP address from hostname:
eureka:
  instance:
    prefer-ip-address: true