spring:
  # activate discovery locator functionalities
  # So it will fetch registered microservice
  # from eureka server.
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: on


      # configure cors:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

# occupation port:
server:
  port: 8888

# register to eureka with IP address:
eureka:
  instance:
    prefer-ip-address: true
